language: node_js
node_js:
  - "lts/*"
  - "9"
  - "lts/carbon"
  - "lts/boron"
before_install:
  - npm i -g npm@latest
  - npm i -g yarn@latest
script:
  - yarn run cover
after_script:
  - yarn run coveralls
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
