language: node_js
node_js:
  - "lts/*"
  - "node"
  - "8"
before_install:
  - npm i -g npm@latest
  - npm i -g yarn@latest
script:
  - yarn test-travis
deploy:
  provider: npm
  email: manuel@schaechinger.com
  api:key: $NPM_TOKEN
  on:
    tags: true
